# Generated by Django 5.2.1 on 2025-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoPro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newuser',
            field=models.CharField(default='Anonymous', max_length=20),
            preserve_default=False,
        ),
    ]
