# Generated by Django 5.2.1 on 2025-06-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoPro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example slug', unique=True),
            preserve_default=False,
        ),
    ]
