# Generated by Django 5.2.1 on 2025-06-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoPro', '0002_post_newuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='newuser',
        ),
    ]
