# Generated by Django 5.2.1 on 2025-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoPro', '0003_remove_post_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorage',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
